wandb_version: 1

_content:
  desc: null
  value:
    data_params: '{''name'': ''roc_stories_genslm'', ''include_section_ids_in_tokenizer'':
      True, ''data_seed'': 1337, ''k'': 5, ''shuffle'': True}'
    experiment_params: '{''validate'': True, ''checkpoint_epochs'': 1, ''continue_from_checkpoint'':
      True, ''num_epochs'': 5, ''cuda'': True, ''seed'': 28289, ''data_loader_workers'':
      0}'
    loss_params: '{''loss'': ''cbow_diff_genslm'', ''name'': ''simclr''}'
    model_params: '{''encoder'': ''cl'', ''latent_dim'': 32, ''n_layers'': 2, ''eps'':
      1e-06, ''hidden_size'': 128, ''language_encoder'': ''GPT2NeoX'', ''filepath'':
      None, ''pretrained_name'': None, ''single_layer'': False, ''finetune_gpt2'':
      False, ''use_log'': False}'
    optim_params: '{''batch_size'': 16, ''decay_steps'': 50000.0, ''decay_factor'':
      0.1, ''learning_rate'': 0.0005, ''moving_average_decay'': 0.9999, ''momentum'':
      0.9}'
    wandb_settings: '{''exp_name'': ''encoder_training_requires_grad_single_layer'',
      ''exp_dir'': ''/home/jiongxiao//genome_results/encoder_genslm_28289/run_l0.0005_b32_cbow_diff/'',
      ''project'': ''language_modeling_via_stochastic_processes'', ''group'': ''encoder'',
      ''dryrun'': True}'
_flags_cache:
  desc: null
  value:
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=None, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2023-09-20'', (''%H-%M-%S'',): ''21-42-36''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: huggingface
    huggingface_version: 4.8.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    t:
      1:
      - 1
      - 9
      - 11
      4: 3.8.18
      5: 0.10.23
      6: 4.8.0.dev0
      8:
      - 5
