6.11 45.67 5.23 export BSZ=32; export LR=0.0001; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_finetune_gpt2_single_layer_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 model_params.single_layer=True model_params.finetune_gpt2=True optim_params.learning_rate=$LR optim_params.batch_size=$BSZ > fixval_logs/log.finetune_gpt2.single_layer.lr${LR}.bsz${BSZ} 2>&1&
5.74 47.57 5.19 export BSZ=32; export LR=0.0005; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_finetune_gpt2_single_layer_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 model_params.single_layer=True model_params.finetune_gpt2=True optim_params.learning_rate=$LR optim_params.batch_size=$BSZ > fixval_logs/log.finetune_gpt2.single_layer.lr${LR}.bsz${BSZ} 2>&1&
6.03 45.37 5.24 export BSZ=32; export LR=0.001; CUDA_VISIBLE_DEVICES=1 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_finetune_gpt2_single_layer_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 model_params.single_layer=True model_params.finetune_gpt2=True optim_params.learning_rate=$LR optim_params.batch_size=$BSZ > fixval_logs/log.finetune_gpt2.single_layer.lr${LR}.bsz${BSZ} 2>&1&
5.71 45.71 5.20 export BSZ=32; export LR=0.002; CUDA_VISIBLE_DEVICES=2 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_finetune_gpt2_single_layer_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 model_params.single_layer=True model_params.finetune_gpt2=True optim_params.learning_rate=$LR optim_params.batch_size=$BSZ > fixval_logs/log.finetune_gpt2.single_layer.lr${LR}.bsz${BSZ} 2>&1&
5.95 45.51 5.19 export BSZ=32; export LR=0.005; CUDA_VISIBLE_DEVICES=3 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_finetune_gpt2_single_layer_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 model_params.single_layer=True model_params.finetune_gpt2=True optim_params.learning_rate=$LR optim_params.batch_size=$BSZ > fixval_logs/log.finetune_gpt2.single_layer.lr${LR}.bsz${BSZ} 2>&1&


7.57 36.79 5.18 export BSZ=32; export LR=0.0001; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&
7.00 39.40 5.08 export BSZ=32; export LR=0.0005; CUDA_VISIBLE_DEVICES=1 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&
6.84 40.42 5.07 export BSZ=32; export LR=0.001; CUDA_VISIBLE_DEVICES=2 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&
6.75 39.61 5.13 export BSZ=32; export LR=0.002; CUDA_VISIBLE_DEVICES=3 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&
8.19 35.19 5.34 export BSZ=32; export LR=0.005; CUDA_VISIBLE_DEVICES=2 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&




# Fix Preprocessing
7.18 38.05 5.27 4.71 4.82 export BSZ=32; export LR=0.0001; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixpre_fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixpre_fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&

6.71 41.61 5.17 4.63 4.80 export BSZ=32; export LR=0.0005; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow wandb_settings.exp_dir=fixpre_fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixpre_fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&

6.77 40.34 5.19 4.67 4.85 export BSZ=32; export LR=0.001; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow  wandb_settings.exp_dir=fixpre_fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixpre_fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&

6.42 41.92 5.22 4.74 4.97 export BSZ=32; export LR=0.002; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow  wandb_settings.exp_dir=fixpre_fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixpre_fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&

7.80 36.84 5.41 4.84 5.00  export BSZ=32; export LR=0.005; CUDA_VISIBLE_DEVICES=0 python scripts/train_encoder.py --config-name=cbow  wandb_settings.exp_dir=fixpre_fixval_wikisection_tc32_cbow_${LR}_${BSZ} data_params.name=wikisectioncbow model_params.latent_dim=32 optim_params.learning_rate=${LR} > fixpre_fixval_logs/log.vanilla.lr${LR}.bsz${BSZ} 2>&1&

# gpt2-small: 0.0005; gpt2-medium: 0.0005, gpt2-large: 0.0005
